AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ScrapeNewsFunction:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: scrape_news
      Handler: scrape_news.lambda_handler
      Runtime: python3.8
      Role: arn:aws:iam::your-account-id:role/your-lambda-role
      Code:
        S3Bucket: your-lambda-code-bucket
        S3Key: scrape_news.zip
      Environment:
        Variables:
          ENV_VAR_EXAMPLE: value

  GenerateArticleFunction:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: generate_article
      Handler: generate_article.lambda_handler
      Runtime: python3.8
      Role: arn:aws:iam::your-account-id:role/your-lambda-role
      Code:
        S3Bucket: your-lambda-code-bucket
        S3Key: generate_article.zip
      Environment:
        Variables:
          ENV_VAR_EXAMPLE: value

  ParaphraseArticleFunction:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: paraphrase_article
      Handler: paraphrase_article.lambda_handler
      Runtime: python3.8
      Role: arn:aws:iam::your-account-id:role/your-lambda-role
      Code:
        S3Bucket: your-lambda-code-bucket
        S3Key: paraphrase_article.zip
      Environment:
        Variables:
          ENV_VAR_EXAMPLE: value

  NotifyEditorFunction:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: notify_editor
      Handler: notify_editor.lambda_handler
      Runtime: python3.8
      Role: arn:aws:iam::your-account-id:role/your-lambda-role
      Code:
        S3Bucket: your-lambda-code-bucket
        S3Key: notify_editor.zip
      Environment:
        Variables:
          ENV_VAR_EXAMPLE: value

  OptimizeSeoFunction:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: optimize_seo
      Handler: optimize_seo.lambda_handler
      Runtime: python3.8
      Role: arn:aws:iam::your-account-id:role/your-lambda-role
      Code:
        S3Bucket: your-lambda-code-bucket
        S3Key: optimize_seo.zip
      Environment:
        Variables:
          ENV_VAR_EXAMPLE: value

  PublishArticleFunction:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: publish_article
      Handler: publish_article.lambda_handler
      Runtime: python3.8
      Role: arn:aws:iam::your-account-id:role/your-lambda-role
      Code:
        S3Bucket: your-lambda-code-bucket
        S3Key: publish_article.zip
      Environment:
        Variables:
          ENV_VAR_EXAMPLE: value

  PostToSocialMediaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: post_to_social_media
      Handler: post_to_social_media.lambda_handler
      Runtime: python3.8
      Role: arn:aws:iam::your-account-id:role/your-lambda-role
      Code:
        S3Bucket: your-lambda-code-bucket
        S3Key: post_to_social_media.zip
      Environment:
        Variables:
          ENV_VAR_EXAMPLE: value

  ScrapeNewsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/scrape_news
      RetentionInDays: 14

  GenerateArticleLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/generate_article
      RetentionInDays: 14

  ParaphraseArticleLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/paraphrase_article
      RetentionInDays: 14

  NotifyEditorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/notify_editor
      RetentionInDays: 14

  OptimizeSeoLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/optimize_seo
      RetentionInDays: 14

  PublishArticleLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/publish_article
      RetentionInDays: 14

  PostToSocialMediaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/post_to_social_media
      RetentionInDays: 14

  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: LambdaErrorAlarm
      AlarmDescription: "Alarm for Lambda function errors"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: scrape_news
        - Name: FunctionName
          Value: generate_article
        - Name: FunctionName
          Value: paraphrase_article
        - Name: FunctionName
          Value: notify_editor
        - Name: FunctionName
          Value: optimize_seo
        - Name: FunctionName
          Value: publish_article
        - Name: FunctionName
          Value: post_to_social_media
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SNSAlarmTopic
      OKActions:
        - !Ref SNSAlarmTopic

  LambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: LambdaDurationAlarm
      AlarmDescription: "Alarm for Lambda function duration"
      Namespace: AWS/Lambda
      MetricName: Duration
      Dimensions:
        - Name: FunctionName
          Value: scrape_news
        - Name: FunctionName
          Value: generate_article
        - Name: FunctionName
          Value: paraphrase_article
        - Name: FunctionName
          Value: notify_editor
        - Name: FunctionName
          Value: optimize_seo
        - Name: FunctionName
          Value: publish_article
        - Name: FunctionName
          Value: post_to_social_media
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1000
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SNSAlarmTopic
      OKActions:
        - !Ref SNSAlarmTopic

  SNSAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: LambdaAlarmsTopic

  CloudWatchLogsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudWatchLogsPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:log-group:/aws/lambda/*
      Roles:
        - !Ref LambdaExecutionRole

  CloudWatchAlarmsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudWatchAlarmsPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricAlarm
              - cloudwatch:DeleteAlarms
              - sns:Publish
            Resource: '*'
      Roles:
        - !Ref LambdaExecutionRole

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - ses:SendEmail
                  - sns:Publish
                Resource: '*'
      Path: /

  ScrapeNewsEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: ScrapeNewsScheduleRule
      ScheduleExpression: rate(12 hours)
      State: ENABLED
      Targets:
        - Arn: !GetAtt ScrapeNewsFunction.Arn
          Id: ScrapeNewsFunctionTarget

  PermissionForEventsToInvokeScrapeNews:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ScrapeNewsFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScrapeNewsEventRule.Arn

  GenerateArticleEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: GenerateArticleRule
      EventPattern:
        source:
          - "aws.lambda"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "lambda.amazonaws.com"
          eventName:
            - "Invoke"
          requestParameters:
            functionName:
              - !Ref ScrapeNewsFunction
      State: ENABLED
      Targets:
        - Arn: !GetAtt GenerateArticleFunction.Arn
          Id: GenerateArticleFunctionTarget

  PermissionForEventsToInvokeGenerateArticle:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GenerateArticleFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt GenerateArticleEventRule.Arn

  ParaphraseArticleEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: ParaphraseArticleRule
      EventPattern:
        source:
          - "aws.lambda"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "lambda.amazonaws.com"
          eventName:
            - "Invoke"
          requestParameters:
            functionName:
              - !Ref GenerateArticleFunction
      State: ENABLED
      Targets:
        - Arn: !GetAtt ParaphraseArticleFunction.Arn
          Id: ParaphraseArticleFunctionTarget

  PermissionForEventsToInvokeParaphraseArticle:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ParaphraseArticleFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ParaphraseArticleEventRule.Arn

  NotifyEditorEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: NotifyEditorRule
      EventPattern:
        source:
          - "aws.lambda"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "lambda.amazonaws.com"
          eventName:
            - "Invoke"
          requestParameters:
            functionName:
              - !Ref ParaphraseArticleFunction
      State: ENABLED
      Targets:
        - Arn: !GetAtt NotifyEditorFunction.Arn
          Id: NotifyEditorFunctionTarget

  PermissionForEventsToInvokeNotifyEditor:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref NotifyEditorFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt NotifyEditorEventRule.Arn

  OptimizeSeoEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: OptimizeSeoRule
      EventPattern:
        source:
          - "aws.lambda"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "lambda.amazonaws.com"
          eventName:
            - "Invoke"
          requestParameters:
            functionName:
              - !Ref NotifyEditorFunction
      State: ENABLED
      Targets:
        - Arn: !GetAtt OptimizeSeoFunction.Arn
          Id: OptimizeSeoFunctionTarget

  PermissionForEventsToInvokeOptimizeSeo:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref OptimizeSeoFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt OptimizeSeoEventRule.Arn

  PublishArticleEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: PublishArticleRule
      EventPattern:
        source:
          - "aws.lambda"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "lambda.amazonaws.com"
          eventName:
            - "Invoke"
          requestParameters:
            functionName:
              - !Ref OptimizeSeoFunction
      State: ENABLED
      Targets:
        - Arn: !GetAtt PublishArticleFunction.Arn
          Id: PublishArticleFunctionTarget

  PermissionForEventsToInvokePublishArticle:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PublishArticleFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt PublishArticleEventRule.Arn

  PostToSocialMediaEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: PostToSocialMediaRule
      EventPattern:
        source:
          - "aws.lambda"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "lambda.amazonaws.com"
          eventName:
            - "Invoke"
          requestParameters:
            functionName:
              - !Ref PublishArticleFunction
      State: ENABLED
      Targets:
        - Arn: !GetAtt PostToSocialMediaFunction.Arn
          Id: PostToSocialMediaFunctionTarget

  PermissionForEventsToInvokePostToSocialMedia:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PostToSocialMediaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt PostToSocialMediaEventRule.Arn
